<?php

function room_specs($id=0){
	$specs = array(
		'1'	=> lang('ACTIVITIES_OLDER_CHILDREN'),
		'2' => lang('ACTIVITIES_YOUNG_CHILDREN'),
		'3' => lang('ADJOINING_ROOMS'),
		'4' => lang('ALL_INCLUSIVE'),
		'5' => lang('ALL_SUITES'),
		'6' => lang('APARTMENTS'),
		'7' => lang('BAR_LOUNGE'),
		'8' => lang('BATHROOMS'),
		'9' => lang('BEACH'),
		'10'=> lang('BED_AND_BREAKFAST'),
		'11'=> lang('BUSINESS_SERVICES'),
		'12'=> lang('CAR_RENTAL_DESK'),
		'13'=> lang('CASTLE'),
		'14'=> lang('CONVENTIONS'),
		'15'=> lang('CREDIT_CARDS_ACCEPTED'),
		'16'=> lang('DATA_PORT'),
		'17'=> lang('DINING'),
		'18'=> lang('DRY_CLEANING'),
		'19'=> lang('EARLY_ARRIVAL'),
		'20'=> lang('ECONOMY'),
		'21'=> lang('ELDER_ACCESS'),
		'22'=> lang('EXTENDED_STAY'),
		'23'=> lang('FAMILY_ROOMS'),
		'24'=> lang('FARM_RANCH'),
		'25'=> lang('FIRST_CLASS'),
		'26'=> lang('FITNESS_CENTER'),
		'27'=> lang('FOOD_AVAILABLE'),
		'28'=> lang('FREE_BREAKFAST'),
		'29'=> lang('FREE_CANCELATION'),
		'30'=> lang('FREE_INTERNET'),
		'31'=> lang('FREE_LOCAL_CALLS'),
		'32'=> lang('FREE_PARKING'),
		'33'=> lang('FREE_WIFI'),
		'34'=> lang('GAME_ROOM'),
		'35'=> lang('GOLF'),
		'36'=> lang('HOT_TUB'),
		'37'=> lang('KIDS_ACTIVITIES'),
		'38'=> lang('KITCHEN_KITCHENETTE'),
		'39'=> lang('KITCHENETTE'),
		'40'=> lang('LATE_ARRIVAL'),
		'41'=> lang('LATE_CHECK_OUT'),
		'42'=> lang('LOCKERS_STORAGE'),
		'43'=> lang('LOYALTY_REWARDS_AVAILABLE'),
		'44'=> lang('LUXURY'),
		'45'=> lang('MEALS_INCLUDED'),
		'46'=> lang('MEETING_ROOM'),
		'47'=> lang('MOTEL'),
		'48'=> lang('NON_SMOKING'),
		'49'=> lang('PARKING_AVAILABLE'),
		'50'=> lang('PAID_PARKING'),
		'51'=> lang('PETS_ALLOWED'),
		'52'=> lang('PRIVATE_BATH'),
		'53'=> lang('RESORT'),
		'54'=> lang('RESTAURANT'),
		'55'=> lang('ROOM_SERVICE'),
		'56'=> lang('SHARED_BATH'),
		'57'=> lang('SHUTTLE'),
		'58'=> lang('STAIRS_ELEVATOR'),
		'59'=> lang('STROLLER_PARKING'),
		'60'=> lang('SUITES'),
		'61'=> lang('SWIMMING_POOL'),
		'62'=> lang('ROOM_WITH_A_VIEW'),
		'63'=> lang('TENNIS_COURT'),
		'64'=> lang('VALET_PARKING'),
		'65'=> lang('WHEELCHAIR_ACCESS'));

	if ($id > 0) {
		return $specs[$id];
	}else{
		return $specs;
	}
}

function spec_css($id=0){
	$specs = array(
		'1'	=> 'ACTIVITIES_OLDER_CHILDREN',
		'2' => 'ACTIVITIES_YOUNG_CHILDREN',
		'3' => 'ADJOINING_ROOMS',
		'4' => 'ALL_INCLUSIVE',
		'5' => 'ALL_SUITES',
		'6' => 'APARTMENTS',
		'7' => 'BAR_LOUNGE',
		'8' => 'BATHROOMS',
		'9' => 'BEACH',
		'10'=> 'BED_AND_BREAKFAST',
		'11'=> 'BUSINESS_SERVICES',
		'12'=> 'CAR_RENTAL_DESK',
		'13'=> 'CASTLE',
		'14'=> 'CONVENTIONS',
		'15'=> 'CREDIT_CARDS_ACCEPTED',
		'16'=> 'DATA_PORT',
		'17'=> 'DINING',
		'18'=> 'DRY_CLEANING',
		'19'=> 'EARLY_ARRIVAL',
		'20'=> 'ECONOMY',
		'21'=> 'ELDER_ACCESS',
		'22'=> 'EXTENDED_STAY',
		'23'=> 'FAMILY_ROOMS',
		'24'=> 'FARM_RANCH',
		'25'=> 'FIRST_CLASS',
		'26'=> 'FITNESS_CENTER',
		'27'=> 'FOOD_AVAILABLE',
		'28'=> 'FREE_BREAKFAST',
		'29'=> 'FREE_CANCELATION',
		'30'=> 'FREE_INTERNET',
		'31'=> 'FREE_LOCAL_CALLS',
		'32'=> 'FREE_PARKING',
		'33'=> 'FREE_WIFI',
		'34'=> 'GAME_ROOM',
		'35'=> 'GOLF',
		'36'=> 'HOT_TUB',
		'37'=> 'KIDS_ACTIVITIES',
		'38'=> 'KITCHEN_KITCHENETTE',
		'39'=> 'KITCHENETTE',
		'40'=> 'LATE_ARRIVAL',
		'41'=> 'LATE_CHECK_OUT',
		'42'=> 'LOCKERS_STORAGE',
		'43'=> 'LOYALTY_REWARDS_AVAILABLE',
		'44'=> 'LUXURY',
		'45'=> 'MEALS_INCLUDED',
		'46'=> 'MEETING_ROOM',
		'47'=> 'MOTEL',
		'48'=> 'NON_SMOKING',
		'49'=> 'PARKING_AVAILABLE',
		'50'=> 'PAID_PARKING',
		'51'=> 'PETS_ALLOWED',
		'52'=> 'PRIVATE_BATH',
		'53'=> 'RESORT',
		'54'=> 'RESTAURANT',
		'55'=> 'ROOM_SERVICE',
		'56'=> 'SHARED_BATH',
		'57'=> 'SHUTTLE',
		'58'=> 'STAIRS_ELEVATOR',
		'59'=> 'STROLLER_PARKING',
		'60'=> 'SUITES',
		'61'=> 'SWIMMING_POOL',
		'62'=> 'ROOM_WITH_A_VIEW',
		'63'=> 'TENNIS_COURT',
		'64'=> 'VALET_PARKING',
		'65'=> 'WHEELCHAIR_ACCESS');
	if ($id > 0) {
		return $specs[$id];
	}else{
		return $specs;
	}
}